const ITEMLISTS = [
  {
    id: 1,
    name: "Cây Cam Ngọt Của Tôi",
    price: 75000,
    discount: "-31%",
    reviews: 4.9,
    numberOfReview: "100 lượt đánh giá",
    numberOfSale: "Đã bán 1000",
    quatity: 3,
    status: 1,
    image: require("../../assets/images/chrome-capture-2022-10-21.png"),
    category: "Sách lịch sử",
    categoryDetail: "Lịch sử thế giới",
    productCompany: "Alpha Books",
    releaseDate: "2021-07-14",
    translator: "Nguyễn Thùy Chung",
    coverType: "Bìa mềm",
    numberOfPage: 580,
    editionCompany: "Nhà xuất bản thế giới",
    decription: {
      title: "SAPIENS - LƯỢC SỬ LOÀI NGƯỜI",
      content:
        "Cuốn sách Sapiens - Lược sử loài người dành cho: Những người muốn hiểu về lịch sử tiến hóa và phát triển của loài người. Những người ngưỡng mộ tác giả của cuốn sách là Yuvai Noah Harari.Những người muốn tiếp cận với kho tàng kiến thức khổng lồ, đủ mọi lĩnh vực khoa học",
    },
  },
  {
    id: 2,
    name: "Một Thoáng Ta Rực Rỡ Ở Nhân Gian",
    price: 96300,
    discount: "-29%",
    reviews: 4.8,
    quatity: 2,
    status: 2,
    numberOfReview: "100 lượt đánh giá",
    numberOfSale: "Đã bán 1000",
    image: require("../../assets/images/1thoangonhangian.png"),
    category: "Sách ls",
    categoryDetail: "Lịch sử tg",
    productCompany: "Books Store",
    releaseDate: "2021-07-14",
    translator: "Nguyễn Thùy Chung",
    coverType: "Bìa mềm",
    numberOfPage: 580,
    editionCompany: "Nhà xuất bản thế giới",
    decription: {
      title: "SAPIENS - LƯỢC SỬ LOÀI NGƯỜI",
      content:
        "Cuốn sách Sapiens - Lược sử loài người dành cho: Những người muốn hiểu về lịch sử tiến hóa và phát triển của loài người. Những người ngưỡng mộ tác giả của cuốn sách là Yuvai Noah Harari.Những người muốn tiếp cận với kho tàng kiến thức khổng lồ, đủ mọi lĩnh vực khoa học",
    },
  },
  {
    id: 3,
    name: "Án Mạng Trên Sông Nile",
    price: 94300,
    discount: "-30%",
    reviews: 4.7,
    quatity: 4,
    status: 3,
    numberOfReview: "100 lượt đánh giá",
    numberOfSale: "Đã bán 1000",
    image: require("../../assets/images/anmangtrensongnile.png"),
    category: "Sách lịch sử",
    categoryDetail: "Lịch sử thế giới",
    productCompany: "Alpha Books",
    releaseDate: "2021-07-14",
    translator: "Nguyễn Thùy Chung",
    coverType: "Bìa mềm",
    numberOfPage: 580,
    editionCompany: "Nhà xuất bản thế giới",
    decription: {
      title: "SAPIENS - LƯỢC SỬ LOÀI NGƯỜI",
      content:
        "Cuốn sách Sapiens - Lược sử loài người dành cho: Những người muốn hiểu về lịch sử tiến hóa và phát triển của loài người. Những người ngưỡng mộ tác giả của cuốn sách là Yuvai Noah Harari.Những người muốn tiếp cận với kho tàng kiến thức khổng lồ, đủ mọi lĩnh vực khoa học",
    },
  },
  {
    id: 4,
    name: "Mã 612: Ai Đã Giết Hoàng Tử Bé",
    price: 91700,
    discount: "-27%",
    reviews: 4.9,
    quatity: 3,
    status: 4,
    numberOfReview: "100 lượt đánh giá",
    numberOfSale: "Đã bán 1000",
    image: require("../../assets/images/aidagiethoangtube.png"),
    category: "Sách lịch sử",
    categoryDetail: "Lịch sử thế giới",
    productCompany: "Alpha Books",
    releaseDate: "2021-07-14",
    translator: "Nguyễn Thùy Chung",
    coverType: "Bìa mềm",
    numberOfPage: 580,
    editionCompany: "Nhà xuất bản thế giới",
    decription: {
      title: "SAPIENS - LƯỢC SỬ LOÀI NGƯỜI",
      content:
        "Cuốn sách Sapiens - Lược sử loài người dành cho: Những người muốn hiểu về lịch sử tiến hóa và phát triển của loài người. Những người ngưỡng mộ tác giả của cuốn sách là Yuvai Noah Harari.Những người muốn tiếp cận với kho tàng kiến thức khổng lồ, đủ mọi lĩnh vực khoa học",
    },
  },

  {
    id: 5,
    name: "Mã 612: Ai Đã Giết Hoàng Tử Bé",
    price: 91700,
    discount: "-27%",
    reviews: 4.9,
    quatity: 4,
    status: 1,
    numberOfReview: "100 lượt đánh giá",
    numberOfSale: "Đã bán 1000",
    image: require("../../assets/images/aidagiethoangtube.png"),
    category: "Sách lịch sử",
    categoryDetail: "Lịch sử thế giới",
    productCompany: "Alpha Books",
    releaseDate: "2021-07-14",
    translator: "Nguyễn Thùy Chung",
    coverType: "Bìa mềm",
    numberOfPage: 580,
    editionCompany: "Nhà xuất bản thế giới",
    decription: {
      title: "SAPIENS - LƯỢC SỬ LOÀI NGƯỜI",
      content:
        "Cuốn sách Sapiens - Lược sử loài người dành cho: Những người muốn hiểu về lịch sử tiến hóa và phát triển của loài người. Những người ngưỡng mộ tác giả của cuốn sách là Yuvai Noah Harari.Những người muốn tiếp cận với kho tàng kiến thức khổng lồ, đủ mọi lĩnh vực khoa học",
    },
  },
];
export default ITEMLISTS;
